# Config
TOKEN = 'PRODUCTIONBOTTOKENHERE'
DEV_TOKEN = 'DEVBOTTOKENHERE'
ENVIRONMENT = 'PROD'
CLIENT_KEY_PTERO = 'CLIENTAPIKEY'
APP_KEY_PTERO = 'APPLICATIONAPIKEY'
BASE_URL = 'BASEURLFORPTEROPANEL'
CF_CLIENT_ID = 'CLIENTIDCLOUDFLARE'  # Only need this if you have cloudflare
CF_CLIENT_SECRET = 'CLIENTSECRETCLOUDFLARE'  # Only need this if you have cloudflare
DB_USERNAME = "USERNAME"  # Username for Database
DB_PASSWORD = "********"  # Password for Database
DB_IP = "127.0.0.1"  # Ip of Database
DB_NAME = "NAME"  # Name of Database
VC_CATEGORY = 999999999999
