# Config
TOKEN = 'PRODUCTIONBOTTOKENHERE'
DEV_TOKEN = 'DEVBOTTOKENHERE'
ENVIRONMENT = 'PROD'
CLIENT_KEY_PTERO = 'CLIENTAPIKEY'
APP_KEY_PTERO = 'APPLICATIONAPIKEY'
BASE_URL = 'BASEURLFORPTEROPANEL'
CF_CLIENT_ID = 'CLIENTIDCLOUDFLARE'  # Only need this if you have cloudflare
CF_CLIENT_SECRET = 'CLIENTSECRETCLOUDFLARE'  # Only need this if you have cloudflare
